[project]
name = "dev-site"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django==4.2.20",
    "django-debug-toolbar>=5.1.0",
    "ipython>=9.1.0",
    "pillow>=11.2.1",
    "psycopg2>=2.9.10",
]
